### ISSUE TITLE
Strange behavior of the "cycle(input: .. ") method

### ISSUE THREAD

**Issue by rezuantpr** [danielt1263/CLE-Architecture-Tools#6]
Hello,

I am trying to implement a "state machine" pattern. I found the necessary tools for that in this library. 
However, in the process I get strange behavior of this method:

```
cycle<State, Input>(
	input: Observable<Input>,
	initialState: State,
	reduce: @escaping (inout State, Input) -> Void,
	reaction: @escaping Reaction<State, Input>
)
```

Look at the screen image where I get the results in the wrong order. After "20" I expect to see "21, 22, ..." (a new page), but I get the first page twice.

It may also not react to my actions or react twice to the single action.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/28421025/210898600-3429e247-c589-4e7f-baaf-441fbbb49349.png">

I have had experience with the [RxFeedback](https://github.com/NoTests/RxFeedback.swift/) framework and I find this approaches very similar (or not?).

So I tried to use RxFeedback for the same purpose and it works fine.

I assume I made some mistakes in the CLE approach, but I can't figure it out, because I'm new to "unidirectional systems".

For the demonstration I prepared a classic "infinite scroll" project using both approaches. The source code of identical, but the result is not.

I think it would be better if I show my repository with a simple demo project. 
https://github.com/rezuantpr/RxFeedback-vs-CLE

Thanks for any help

P.s. Just compare "RxFeedbackPagingViewModel.swift" and "CLEPagingVewModel.swift" files.

**Comment by danielt1263** [comment]
There is a fundamental difference between `cycle` and every other feedback system out there (RxFeedback, TCA's Store type, RxFlow and even Redux) in that the `reaction` of cycle is *not* a [Moore machine](https://en.wikipedia.org/wiki/Moore_machine). Instead it models a [Mealy state machine](https://en.wikipedia.org/wiki/Mealy_machine).

This means that instead of receiving the state after it has been modified by the input, you get the state from *before* the input along with the input.

So for the example you provided, instead of the reaction being `{ state, _ in state.shouldLoadNext ? state.page : nil }`, it should be `{ state, event in event == .loadNext ? state.page : nil }` (PagingEvent has to be made equatable for this to work.)

Note that because of the way `cycle` works, you don't need as much state. So for example in this case, the cycle doesn't need the `shouldLoadNext` or `nextPage` state at all.

Hope this helps. Thank you for providing sample code and thank you for trying out the library! If you have any other questions, I'm happy to answer.

**Comment by rezuantpr** [comment]
Thanks, I had completely forgotten about the Moore and Mealy machines. I studied them at university many years ago :)

Sorry for such questions, if I could  find any example of "cycle" usage, I wouldn't ask them. 

I appreciate it very much, but where can I ask questions if I had? Opening new issues every time for no reason isn't a good idea.

**Comment by danielt1263** [comment]
Sorry. Yeah the documentation is quite lacking. A pull request with documentation would be warmly accepted 🙂. 

You can ask here for sure. Also the RxSwift slack has a dedicated channel to CLE. Maybe Stack Overflow but we would need to create a tag for it.
